### ISSUE TITLE
Not submitting and making a get request

### ISSUE THREAD

**Issue by umutzd** [punkave/apostrophe-pieces-submit-widgets#12]
Everything works OK, except the widget does not submit and makes a page refresh get request (with form data) on the same page.

I added some console.log checks on `/node_modules/apostrophe-pieces-submit-widgets/public/js/user.js`: 

```js
    self.play = function($widget, data, options) {
      console.log($widget);
      var $form = $widget.find('[data-apos-pieces-submit-form]');
      console.log("-------");
      console.log($form);
      console.log("-------");
      var schema = self.options.submitSchema;
      var piece = _.cloneDeep(self.options.piece);
      return apos.schemas.populate($form, schema, piece, function(err) {
        if (err) {
          apos.utils.error('For setup error: ', err);
          alert('A problem occurred setting up the contact form.');
          return;
        }
```

$widget is outputting and fine. But the $form is something that its `length` is `0`. No event or submit handlers run. My overridden widget.html file: 

```nunjucks
{% import "apostrophe-schemas:macros.html" as schemas %}

<form method="post" class="apos-submit-pieces-form apos-ui" data-apos-pieces-submit-form>
  {# <h4>{{ data.label }}</h4> #}
  {{ schemas.fields(data.schema, { tabs: false }) }}
  <input type="submit" value="Submit">
  {# <button>Submit</button> #}
  {# Later gets hoisted out and becomes visible #}
  <div class="apos-pieces-submit-thank-you" data-apos-pieces-submit-thank-you>
    <h4>Thank you for your submission! We will review it soon.</h4>
  </div>
</form>
```

And If I remove the file to use the default widget.html file, nothing changes.

**Comment by abea** [comment]
Are you making these overrides in the `apostrophe-pieces-submit-widgets` module directly, or on the new module that extends it? I think it's mean to be extended and for your project-level work to be done in the new module.

**Comment by umutzd** [comment]
I am extending the widget as described in the documentation. I don't edit code on node_modules except for testing the module

**Comment by umutzd** [comment]
Problem solved by removing any wrapper form element that wraps the widget singleton from outsite. The outer form overrides the behavior of inside form.
