### ISSUE TITLE
without extend it throws an error

### ISSUE THREAD

**Issue by lasharela** [punkave/apostrophe-pieces-submit-widgets#13]
Base on documentation: 

```
'apostrophe-events': {
    // Let's add an attachment field so the user can upload an image
    addFields: [
      {
        name: 'image',
        type: 'attachment',
        group: 'images',
        required: true
      }
    ]
  },
```

apostrophe-events is not extended from `apostrophe-pieces`. without this, it throws an error

**Comment by boutell** [comment]
Did you ever install the apostrophe-events npm module?

**Comment by boutell** [comment]
It sounds like the module just wasn't installed, but feel free to provide more details on how to reproduce this if I'm wrong.
